### ISSUE TITLE
About NAMESPACE

### ISSUE THREAD

**Issue by adamlei** [eddelbuettel/rcppnloptexample#1]
Hey all,
I am very new to the R package.
 I try  `Rcpp::Rcpp.package.skeleton("mypackage",cpp_files = "nlopt.cpp")` to create a Rcpp package.
But I found there is no` LinkingTo:  nloptr (>= 1.2.0)` in the DESCRIPTION file.

May I ask the `import("nloptr")` in NAMESPACE is added by hand? 

Thank you so much for helping in advance.

**Comment by eddelbuettel** [comment]
We would prefer if you asked _usage_ questions on the rcpp-devel mailing list which is open for all (and you just need to subscribe to post).

In short, because working with NLopt efficiently involves a few small but important steps I would recommend studying _this repo_ carefully and adapting what you get from a (plain, just Rcpp) `Rcpp.package.skeleton()` call.  I am sure you figure out the differences.  Let us know (preferably on the list) if you have more question,

I will close this 'issue' as there is no issue with the package here.  Thanks for your understanding.
